pluginManagement { repositories { gradlePluginPortal(); mavenCentral() } }
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories { mavenCentral() }
}
rootProject.name = 'quorumfs'
['protocol', 'hash-ring', 'versioning', 'storage', 'coordinator', 'replication', 'server', 'client'].each {
    include it
    project(":$it").projectDir = file("modules/$it")
}
